// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNiZXX1S5TdK3w5AJ0Q1HfUldh1gTXOHw',
    appId: '1:3270003709:web:77b363c5add0b6a3216794',
    messagingSenderId: '3270003709',
    projectId: 'wellbeing-app-2',
    authDomain: 'wellbeing-app-2.firebaseapp.com',
    storageBucket: 'wellbeing-app-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4l_YeSmchzK4zCGu2hJVW-6ILg3CmjsQ',
    appId: '1:3270003709:android:eb4847303b4292e3216794',
    messagingSenderId: '3270003709',
    projectId: 'wellbeing-app-2',
    storageBucket: 'wellbeing-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwXVYR2uvKC8NFIA_lm87nDQzMT-PejY',
    appId: '1:3270003709:ios:4279f6ea12e3dcff216794',
    messagingSenderId: '3270003709',
    projectId: 'wellbeing-app-2',
    storageBucket: 'wellbeing-app-2.appspot.com',
    iosClientId: '3270003709-1e2sa9nr50ljrl2n6gbish0vgcgl3ml7.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellbeingApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdwXVYR2uvKC8NFIA_lm87nDQzMT-PejY',
    appId: '1:3270003709:ios:0322aaebc68d274c216794',
    messagingSenderId: '3270003709',
    projectId: 'wellbeing-app-2',
    storageBucket: 'wellbeing-app-2.appspot.com',
    iosClientId: '3270003709-m5m1pepn3qpr6b9fghg9cngsa31bqre4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellbeingApp2.RunnerTests',
  );
}
